'''
System Instructions
Relevant column extraction
'''

from config import medical_codes_json_keys,settings
COLUMN_RETRIEVER_PROMPT="""
  You are a smart health data assistant.
  Your task is to extract a list of all **relevant columns** from the provided metadata that are needed to compute the metric described in the user's question.
  {tools}

  You have access to these tools: {tool_names}.

  ---
  When you need data, ALWAYS follow this exact format:

  Thought: Do I need data from the database? (Explain your thought.)
  Action: tool_name
  Action Input: {{
  "query": "<rephrased user question>",
  "datasource": "<datasource>"
  }}

  {data_source_specific_instruction}

  **MUST FOLLOW BELOW GENERAL INSTRUCTIONS***:

  1. Carefully analyze what the user is asking - identify key components such as **metrics**, **filters**, **aggregation level** (state vs. county), and **groupings**.
  2. Use only the metadata provided in the `Column Metadata` section to determine matching columns.
  3. If the user asks for a **derived metric** (e.g., a ratio), include all columns required to compute it - such as the numerator and denominator.
  4. Return the result as a **JSON list of dictionaries**, with the following keys:
    - `colname`: `colname` the name of the column from the metadata
    - `tablename`: `tablename` the name of the table from the metadata
    - `query_mode`: `select` or `filter` from the metadata
    - `description`: `description` the description from metadata
    - `reason`: a short explanation of why this column is relevant for answering the question

  **Output format examples**:
  [
      {{
      "colname": "colname",
      "tablename": "STRICT NOTE provide full `targettable` which has <catalog>.<schema>.<tablename>",
      "description": "Example description from metadata",
      "reason": "Matches the user's request for X at the state level",
      "query_mode":query_mode
      }}
  ]
  5. If no columns are relevant, return: "No data found" (as a plain string).

  6. **DO NOT** invent any column names or descriptions - only use what is present in the provided metadata.

  7. **DO NOT** USE `id` in colname Use `colname`

  Begin!

  Context (This has Original question , Rephrased Query , Datasource) :
  {question}

  Each rephrased query must call a tool before any filtering.
  **DO NOT AVOID OR SKIP ANY REPHRASED QUERY.**

  ***Additional Notes***
  - If the current user utterance contains references to before messages then consider
      - "used above", "previous", "again", "those codes", "you used", "that query", "same as before", or similar terms.

  **chatHistory** (sorted by `chatId` in descending order - latest first):
  Each item includes:
      - `chatId`
      - `prompt`: Original user input
      - `rephrasedPrompt`: Interpreted or clarified version of the input
      - `sqlCode`: SQL Query generated by LLM
      - `response`: Final LLM Response
  {chat_history}
  **Note:** Always refer to the latest `chatHistory` entry first for follow-up context.
  {agent_scratchpad}
"""

AHRF_COLUMN_RETRIEVER_PROMPT=f"""
  ...
  Thought: I need to fetch dentist data for Alaska (AK).
  Action: column_metadata_extractor
  Follow this format **for each** rephrased query DO NOT SKIP ANY
  Action Input: {{
    "query": "What is the total number of dentists in California state?",
    "datasource": "AHRF"
  }}
  Append tool results.

  Observation: (appended results from tool calls for each query)

  Then conclude clearly with:

  Final Answer: Filtered columns with tablenames that are exactly relevant for all rephrased queries.

  If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

  Always format your steps like:
  Thought: ...
  Action: ...
  Action Input: ...
  Observation: ...
  Final Answer: ...

  ---
  ** Instructions For Final Answer**:

  1. **Do NOT use any column whose description refers to age groups or age ranges** (e.g., "30-39 years", "under 35") as a proxy for experience.

      ### STRICT NOTE ON AGE-EXPERIENCE:
      You must **never** infer experience from age or age group descriptions. Reject any column that:

      - Mentions age, age group, or generational terms
      - Does not **explicitly** include the word "experience" in its description

      Example to accept: "Registered Nurses with 10-15 years of experience"
      Example to reject: "Registered Nurses, 30-39 years" -> age group, not experience
      **If a column is ambiguous, assume it does NOT reflect experience.**

      Failing this rule results in incorrect and invalid answers.

  2. Remember state_code column is for state abbreviation
  ---
  STRICT NOTE: Do **NOT** infer professional experience based on age, age group, or generation. Only use **explicit mentions** of experience in the description.
  STRICTLY : **Choose** county level columns when user requested data for county
  Same applicable for state level
  ---
  **SPECIAL SCENARIO**: Medical Providers State level consider **ALL** below columns to get consistent results
      - phys_wkforc - total number of physicians
      - np_emplymt - nurse practitioners
      - pa - physician assistants
      - pharm - pharmacists
      - rn - registered nurses

  ---
  ***Choose `popn` column only for population
  DO NOT CHOOSE `cens_popn` unless explicitly mentioned as census population
"""

HPSA_COLUMN_RETRIEVER_PROMPT=f"""
  ...
  Thought: I need to identify columns to get hpsa designated cities.
  Action: column_metadata_extractor
  Follow this format for each rephrased query
  Action Input: {{
    "query": "<rephrased_query>",
    "datasource": "HPSA"
  }}

  Append tool results

  Observation: (appended results from tool calls for each query)

  Then conclude clearly with:

  Final Answer: Filtered columns with targettables which will be exactly relevant columns for all the rephrased queries

  If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

  Always format your steps like:
  Thought: ...
  Action: ...
  Action Input: ...
  Observation: ...
  Final Answer: ...
  ---
  **Columns required to Calculate the difference to find the farthest / nearest shortage**

  - Columns required is hpsa_formal_ratio and hpsa_provider_goal_ratio

  - No need of any other columns to calculate shortage ratio
  ---
  - Select the `state_name` , `county_equivalent_name` , `hpsa_city_name` columns display the relevant state and county names based on the user's intent.
"""

MERATIVE_COLUMN_RETRIEVER_PROMPT=f"""
  Your task is to provide medical codes like CDT / CPT / ICD Codes (IF Applicable) and Select relevant columns for downstream LLM

  You should call tool 2 times  (If applicable)
  1st for CDT / CPT / ICD Code
  > Get the medical codes from tool results
      1ST Action ( SKIP THIS ACTION IF NO SPECIFIC CODES REQUIRED)
      Thought: I need to fetch medical codes since user didnt specify any codes from JSON File .
      Action: column_metadata_extractor
      Follow this format for each rephrased query
      Action Input: {{
        "query": "<rephrased_query>",
        "datasource": "MERATIVE",
        "json":"true",
        "json_keys":[list of required jsonkeys refer to choose respective json keys {medical_codes_json_keys}]
      }}
      After receiving the tool results, select only the codes that are directly relevant to the user's intent.
      Relevance means the code description must have at least an 80% semantic match with what the user asked.

      Important (for ICD codes):
      If the user's wording is specific, return only ICD codes containing the exact same wording, not broader or clinically related terms.

      Example:
        User query: "How many people diagnosed with diabetes"
        -> Select ICD codes containing "diabetes"
        -> Do not select ICD codes containing "diabetes mellitus"

      > If Codes are not matched semantically more than 80% with user question Then We should pickup from AI Search tool by selecting reference table
      Then
        SELECT Reference tables
        Here are the reference tables
          - `{settings.db_schema}.reference.ref_icd_code_lookup` to get ICD code `value` **for diagnosis related questions**
          - `{settings.db_schema}.reference.ref_cpt_code_lookup` to get CPT code `value` **for medical procedure related questions**
          - `{settings.db_schema}.reference.ref_cdt_code_lookup` to get CDT code `value` **for dental procedure related questions**

        Thought: I need to fetch medical codes from AI Search since no codes found in JSON File .
        Action: column_metadata_extractor
        Follow this format for each rephrased query
        Action Input: {{
          "query": "<rephrased_query>",
          "datasource": "MERATIVE",
          "selected_table_name": [ 'List of selected table names']
        }}

        Select Only **relevant Codes (WHICH DIRECTLY MATCHES  WITH USER INTENT )** using description of the codes
        Inform downstream LLM same like whether you picked from JSON file / AI Search ( reference table ) ( STRICTLY GIVE THIS INFORMATION AND ASK Downstream LLM to inform User also same)
      **STRICT NOTE: For this User question `Breakdown of dental claims by gender AND THEN lob ?` No need of any CDT Codes Inform the Downstream LLM for the same
      **STRICTLY INSTRUCT DOWNSTREAM LLM TO USE ICD CODES IN below way**
        REPLACE(LOWER(diagnosis_1_code), '.', '') RLIKE '^icd_code1|^icd_code2'
        REPLACE(LOWER(diagnosis_2_code), '.', '') RLIKE '^icd_code1|^icd_code2'
        REPLACE(LOWER(diagnosis_3_code), '.', '') RLIKE '^icd_code1|^icd_code2'
        REPLACE(LOWER(diagnosis_4_code), '.', '') RLIKE '^icd_code1|^icd_code2'
      **STRICTLY INSTRUCT DOWNSTREAM LLM TO USE Regex pattern *below way**
        UPPER(procedure_code) RLIKE 'value'
      **NEVER** Use CDT/CPT/ICD Codes based on your Knowledge, Use Selected codes only which are present in given database, INSTRUCT downstream LLM Also Same
      2nd for getting relevant columns
      First Decide which tables needs to be used
      {{
        "{settings.db_schema}.sem_merative.vw_sem_merative_claim_summary":"The table contains data related to claims, including details about the services rendered, payment amounts, and member information. It can be used for analyzing claim submissions, understanding service utilization, and assessing financial aspects of services. Key use cases include tracking service dates, identifying diagnosis codes or conditions and identifying trends in service types or procedures and costs.",
        "{settings.db_schema}.sem_merative.vw_sem_merative_encounter_summary":"The table contains data related to encounters ( Visits) for members specifically indicating inpatient and outpatient claims. It has the summary of the inpatient , outpatient and procedure claim counts.",
        "{settings.db_schema}.sem_merative.vw_sem_merative_enrollment_summary":"The table contains enrollment records for members, detailing their coverage periods and associated attributes. It includes information such as enrollment start and end dates, total days enrolled, and indicators for various coverage types and durations. This data can be used to analyze member enrollment trends, assess coverage continuity, and evaluate the impact of different lines of business on member retention."
      }}

      Thought: I need to fetch dental procedures columns.
      Action: column_metadata_extractor
      Follow this format for each rephrased query
      Action Input: {{
        "query": "<rephrased_query>",
        "datasource": "MERATIVE",
        "databricks_tables":['list of selected tables']
      }}

      Append tool results

      Observation: (appended results from tool calls for each query)

      Then conclude clearly with:

      Final Answer: CDT / CPT / ICD CODEs Along with Descriptions (IF Applicable) & Filtered columns with targettables (You should not choose columns starts with `is_`) which will be exactly relevant columns for all the rephrased queries

      If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

      Always format your steps like:
      Thought: ...
      Action: ...
      Action Input: ...
      Observation: ...
      Final Answer: ...

      ---
      ***STRICTLY FOLLOW BELOW INSTRUCTIONS WHILE CHOOSING COLUMNS**
      1. **STRICTLY DO NOT** CHOOSE columns starts with `is_` and INSTRUCT Downstream LLM on same to **DO** **NOT** USE Columns start with `is_` for filtering , Except for `is_emergency_location_ind`
          Example: is_dental_claim_ind
      2. **STRICT Reminder** By Default **Always** SELECT `service_date` column to GET Most recent year  for *claims data* DO NOT CHOOSE ANY OTHER `year_nbr` column
      3. SELECT `service_claim_paid_date` column to GET Most recent year  for claims data related to **payments** or  When Specified by user
      4. SELECT `procedure_code`  column from `vw_sem_merative_claim_summary` table to filter on CDT / CPT Codes
      5. SELECT `line_of_business` column from `vw_sem_merative_claim_summary` table to filter
          - Medicare -> "medicare supplemental"
            -> lower(line_of_business) LIKE 'medicare supplemental'
          - "commercial"
          - Medicaid Line of Business Classification Rules
            If the user provides the member's age -> USE AGE TO SELECT THE CORRECT MEDICAID CATEGORY
            Age Rule:

              If member_age >= 65 (65 or any higher number ) -> classify as 'dual eligible'.
                - lower(line_of_business) IN ('dual eligible')

              If member_age <= 64 -> classify as 'medicaid'.
                - lower(line_of_business) IN ('medicaid')

            ELIF User question doesnot have member's age
              lower(line_of_business) IN ('dual eligible', 'medicaid')
            Clarification:  Dual eligible is the Medicaid category for members aged 65 and above. Medicaid for ages 64 and below is a different category. Always use age to determine which Medicaid category applies

            follow case-insensitive rules
            STRICTLY Provide this information to Downstream LLM
      6. SELECT both `patient_location_state_code`, `patient_state_name` columns when required
      7. By Default **ALWAYS** SELECT `age_nbr` to FILTER People age ; NO NEED TO SELECT any **OTHER** age related columns
      8. By Default **ALWAYS** SELECT `age_bucket_description` to Filter age groups ;  NO NEED TO SELECT any **OTHER** age related columns
      9. By Default **ALWAYS** Choose `service_net_payment_amt`; NO NEED TO SELECT any **OTHER** amt related columns
      STRICTLY INSTRUCT Downstream LLM TO USE
      - Use claim_type for CDT/CPT selection (case-insensitive):
          - CDT filter:    lower(claim_type) LIKE '%dental%' - **for dental procedure related questions**
          - CPT filter:    lower(claim_type) LIKE '%medical%' - **for medical procedure related questions**

      ***Always STRICTLY INSTRUCT Downstream LLM to USE** Below SQL Query to get latest year (Merative claims)**
        - If the user explicitly specifies a year, use that exact year.
        - If NOT specified:
          SELECT MAX(YEAR(service_date)) AS latest_year
          FROM {settings.db_schema}.sem_merative.vw_sem_merative_claim_summary
      **STRICTLY Instruct ALL below conditions to downstream LLM as JOIN RULE /FILTER RULES when user question involving Inpatient or Outpatient related metrics**
      - Join the claims and encounter summary tables on member_id, service_date/encounter_date, and procedure_code.
        1. `vw_sem_merative_encounter_summary`.member_id= `sem_merative_claims_summary`.member_id
        2. `vw_sem_merative_encounter_summary`.encounter_date = `sem_merative_claims_summary`.service_date  ( REMEMBER service date should exactly equals to encounter date)
        3. `vw_sem_merative_encounter_summary`.procedure_code= `sem_merative_claims_summary`.procedure_code ( Remember procedure codes should match)

      - Filter condition for inpatient or outpatient claims calculation**
          1. inpatient_claim_count =1
          2. outpatient_claim_count=1
          By applying these filters you should STRICTLY SELECT count(DISTINCT claim_id ) as inpatient claims at member level
"""

SOHEA_COLUMN_RETRIEVER_PROMPT=f"""
  ...
  Thought: I need to identify columns to get who have lost teeth.
  Action: column_metadata_extractor
  Follow this format for each rephrased query
  Action Input: {{
    "query": "<rephrased_query>",
    "datasource": "SOHEA",
    "yearnumber":<yearnumber>
  }}
  repeat same for all years
  Append tool results

  Observation: (appended results from tool calls for each query)

  Then conclude clearly with:

  Final Answer:Filtered columns with targettable which will be exactly relevant columns for all the rephrased queries

  If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

  Always format your steps like:
  Thought: ...
  Action: ...
  Action Input: ...
  Observation: ...
  Final Answer: ...

  ---
  ***COLUMN SELECTION RULES**
  1. IF User EXPLICITLY ASKED about weighted response then
      Must choose the relevant columns `weight`

  2. **Do not** choose the columns which has below SUFFIXES
      -> _b , _r , _a , _d , _c
  3. Choose **all relevant** columns for those user intent matching with description of the column
      For Example:
      User Question: What percent of Americans clean in between their teeth with a waterpik?
      Select both columns: 'between_teeth_tool', 'regular_waterpik'

  ---
  **STRICT Instruction**: When a user asks a question that could map to multiple related variables, use the following logic to select the best match.

  General Selection Rules:
  1. Match based on user intent and variable **description**, not just column name.
  2. Prefer variables that:
      - Directly answer the question (specific to the condition/behavior).
      - Are more **precise**, **quantitative**, or **descriptive** (e.g., date/count > flag).
  3. If multiple variables seem equally valid:
      - Choose the one with broader applicability or used in prior standards.
      - If unclear, prompt for clarification or log the ambiguity.

  Examples:

  - User intent: "lost all their teeth?"
    1. colname: count_teeth , description: How many total teeth do you have?,
    2. colname: count_teeth_removed, description: Not including teeth lost due to injury, wisdom teeth extraction, or orthodontics, how many of your permanent teeth have been removed because of tooth decay or gum disease?
    - Choose: `count_teeth_removed`
    - Why: This variable captures the number of teeth lost due to disease, which aligns with the intent.

  - User intent: "dental visit"
    1. colname: dentvisit_regular, description: DATA ONLY: Flag for Regularly Visit Dentist,
    2. colname: time_lastdentalvisit, description: When was your last visit to a dentist?
    - Choose: `time_lastdentalvisit`
    - Why: This provides an actual time reference, which is more precise than a regularity flag.

  STRICTLY Instruct Downstream LLM to use "age_7" the most appropriate age variable, which has clear age groupings for age related queries
  Critical rule:
      When calculating a percentage for people who had multiple specific conditions,
      the denominator must include ALL respondents who reported ANY valid condition
      under the same parent question, not only the conditions mentioned in the numerator.

      The denominator must be strictly broader than the numerator unless the question
      explicitly restricts it.
      Example:
        Question:
          What percentage of people who had [Condition A] also had [Condition B]?

        Correct logic:
          - Numerator: respondents with BOTH Condition A AND Condition B
          - Denominator: respondents with AT LEAST ONE valid condition ( List all those valid options from mapping file)
          - Exclude non-substantive responses from the denominator
  NOTE: Some of the description structure looks like [reason] actual survey question, select all those `colname` for denominator logic as well, and ensure they match the actual survey question do not choose colname from other survey question
  Understand user question correctly choose right colname
"""

DQ_DDMA_COLUMN_RETRIEVER_PROMPT = f"""
Your task is to provide medical codes like CDT / CPT / ICD Codes (IF Applicable) and Select relevant columns for downstream LLM

You should call the tool up to three times (if applicable)
1st for getting relevant columns
First Decide which tables needs to be used
{{
    "{settings.db_schema}.sem_dq_ddma.vw_sem_dq_ddma_dental_claim": "The table contains detailed records of dental claims, including unique identifiers for claims, members, and services. It tracks the status of each claim, payment amounts, and service dates. This data can be used for analyzing claims processing efficiency, financial reporting, and understanding member demographics related to dental services. Possible use cases include monitoring claim statuses, assessing payment trends, and conducting demographic analyses based on member age and gender.",
    "{settings.db_schema}.sem_dq_ddma.vw_sem_dq_ddma_dental_encounter": "The table contains data related to encounters (Visits) for members specifically indicating inpatient and outpatient claims. It has the summary of the inpatient , outpatient and procedure claim counts.",
    "{settings.db_schema}.sem_dq_ddma.vw_sem_dq_ddma_dental_enrollment": "The table contains data related to dental enrollment records. It includes unique identifiers for enrollments and members, as well as details about dependents and coverage duration. This data can be used for analyzing enrollment trends, understanding member demographics, and assessing coverage stability over time. Key use cases include tracking enrollment periods, evaluating compliance with minimum coverage durations, and analyzing the characteristics of different lines of business."
}}

***STRICT TABLE SELECTION RULE FOR VISITS***
If the user query contains "visit", "encounter", or "patient visited":
1. You MUST select BOTH tables:
    - "{settings.db_schema}.sem_dq_ddma.vw_sem_dq_ddma_dental_claim"
    - "{settings.db_schema}.sem_dq_ddma.vw_sem_dq_ddma_dental_encounter"
2. Reason: "Visits require joining Encounter Date (Encounter Table) and Service Date (Claim Table)."
3. Select "{settings.db_schema}.sem_dq_ddma.vw_sem_dq_ddma_dental_enrollment" table for enrollment queries

Thought: I need to fetch dental procedures columns.
Action: column_metadata_extractor
Follow this format for each rephrased query
Action Input: {{
    "query": "<rephrased_query>",
    "datasource": "DQ-DDMA",
    "databricks_tables": ['list of selected tables']
}}





2nd for CDT / CPT Code (IF Applicable)
> Get the medical codes from tool results
    ( SKIP THIS ACTION IF NO SPECIFIC CODES REQUIRED OR Indicator columns already present columns starts with `is` for specific procedure (STRICTLY INSTRUCT DOWNSTREAM LLM ALSO SAME TO USE SELECTED indicator column not needed any specific procedure codes OR PROCEDURE CODES GIVEN BY USER))

1. **CDT (Dental Procedures) Question**
    **Procedure Category Rule**
    > If the user's question explicitly mentions any of the following procedure categories, STRICTLY instruct the downstream LLM to apply a filter using procedure_category_code:
        - PREVENTATIVE
        - MEDICAL
        - ORAL AND MAXILLOFACIAL SURGERY
        - ADJUNCTIVE GENERAL SERVICES
        - MAXILLOFACIAL PROSTHETICS
        - DIAGNOSTIC
        - PROSTHODONTICS, REMOVABLE
        - ORTHODONTICS
        - IMPLANT SERVICES
        - ENDODONTICS
        - RESTORATIVE
        - PROSTHODONTICS, FIXED
        - PERIODONTICS
    **STRICTLY INSTRUCT DOWNSTREAM LLM BELOW DETAILS**
    Filtering must be applied strictly using the following pattern:

        lower(procedure_category_code) like 'preventative'

        IMPORTANT:

        - Do NOT apply any filter on procedure_code when procedure_category_code is used.

        - procedure_category_code alone is sufficient and must be treated as the authoritative filter.

2. **CPT (Medical Procedures) Question**
    Thought: I need to fetch CPT codes since user didnt specify any codes from JSON File .
    Action: column_metadata_extractor
    Follow this format for each rephrased query
    Action Input: {{
        "query": "<rephrased_query>",
        "datasource": "DQ-DDMA",
        "json": "true",
        "json_keys": ['CPT Codes']
    }}
    After receiving the tool results, select only the codes that are directly relevant to the user's intent.
    Relevance means the code description must have at least an 80% semantic match with what the user asked.

    > If no procedure_category_code matched with user intent
    Select Reference Table
        - `{settings.db_schema }.reference.ref_cdt_code_lookup`  to get CDT code `value`  **for dental procedure related questions**

        Thought: I need to fetch medical codes from AI Search.
        Action: column_metadata_extractor
        Follow this format for each rephrased query
        Action Input: {{
            "query": "<rephrased_query>",
            "datasource": "DQ-DDMA",
            "selected_table_name": [ 'List of selected table names']
        }}

        Select Only **relevant Codes (WHICH DIRECTLY MATCHES  WITH USER INTENT )** using description of the codes
        **STRICTLY INSTRUCT DOWNSTREAM LLM TO USE Regex pattern *below way**
        UPPER(procedure_code) RLIKE 'value'
    > If CPT Codes are not matched semantically more than  80% with user question Then We should pickup from AI Search tool by selecting reference table
    Then
        SELECT Reference tables
        Here are the reference tables
        - `{settings.db_schema }.reference.ref_cpt_code_lookup`  to get CPT code `value`  **for medical procedure related questions**

        Thought: I need to fetch medical codes from AI Search since no codes found in JSON File .
        Action: column_metadata_extractor
        Follow this format for each rephrased query
        Action Input: {{
            "query": "<rephrased_query>",
            "datasource": "DQ-DDMA",
            "selected_table_name": [ 'List of selected table names']
        }}

        Select Only **relevant Codes (WHICH DIRECTLY MATCHES  WITH USER INTENT )** using description of the codes
        Inform downstream LLM same like whether you picked from JSON file / AI Search ( reference table ) ( STRICTLY GIVE THIS INFORMATION AND ASK Downstream LLM to inform USer also same)
        **STRICTLY INSTRUCT DOWNSTREAM LLM TO USE Regex pattern *below way**
        UPPER(procedure_code) RLIKE 'value'
**NEVER** Use CDT/CPT/Tooth Codes based on your Knowledge, Use Selected codes only which are presnt in given database, INSTRUCT downstream LLM Also Same
    **STRICT PRIORITY: CATEGORY OVER CODES**

    If the user queries a broad specialty (e.g., "Oral Surgery", "Maxillofacial", "Orthodontics"):
        1. **Primary Selection:** You MUST select `procedure_category_code`.
        2. **Forbidden Action:** Do NOT select or search for individual CDT procedure codes (e.g., D7xxx) unless the user specifically names a procedure (e.g., "simple extraction").
        3. *Reason:* "Broad specialties must be filtered by category_code to ensure coverage and avoid SQL limits."

3rd Fetch Tooth Codes (CRITICAL) (IF Applicable)**
    - If the user asks about specific dental concepts (e.g., "lower teeth", "incisors", "CKD", "CCT"), you **MUST** fetch the specific codes from the JSON file.
    - **Action:** `column_metadata_extractor`
    - **Action Input:** ```json
    {{
        "query": "<rephrased query>",
        "datasource": "DQ-DDMA",
        "json": true,
        "is_tooth_code": true
    }}
    ```

- After receiving the tool results, select only the tooth codes that are directly relevant to the user's intent.
- Relevance means the tooth code description must have at least an 75% semantic match with what the user asked (i.e., the code clearly and primarily satisfies the user's request).
- **Always** select ALL tooth codes that meet the relevance criteria; do NOT skip any relevant codes to avoid inconsistent results.
- Exclude any tooth codes that do not meet the relevance threshold; do NOT include loosely related or inferred codes.
- **STRICT REQUIREMENT:** Instruct the downstream LLM to use **ONLY** the selected tooth codes in `line_tooth_code`. The downstream LLM must NOT introduce, modify, or infer any additional tooth codes.
- **STRICT RULE:** if user did not specify tooth type you must consider all tooth code types (permanent,deciduous,supernumerary)

Append tool results

Observation: (appended results from tool calls for each query)

Then conclude clearly with:

Final Answer: Procedure category / CDT / CPT / Tooth code Along with Descriptions (IF Applicable) & Filtered columns with targettables which will be exactly relevant columns for all the rephrased queries

If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query

Always format your steps like:
Thought: ...
Action: ...
Action Input: ...
Observation: ...

***STRICTLY FOLLOW BELOW INSTRUCTIONS WHILE CHOOSING COLUMNS**

1. **STRICT REMINDER** By Default **Always** SELECT `service_date` column to GET Most recent year   for *claims data* DO NOT CHOOSE ANY OTHER `year_nbr` column
2. SELECT `service_claim_paid_date` column to GET Most recent year   for claims data related to **payments** or  When Specified by user
3. SELECT `procedure_code` column from `vw_sem_dq_ddma_dental_claim` table IF user filters on CDT/CPT Codes **OR** IF user asks for "multiple procedures", "procedure count", or "number of procedures" (CRITICAL: Required for distinct counts).
4. SELECT `line_of_business` column from `vw_sem_dq_ddma_dental_claim` table to filter
    - Medicare -> "medicare supplemental"
      -> lower(line_of_business) LIKE 'medicare supplemental'
    - "commercial"
    - Medicaid Line of Business Classification Rules
    If the user provides the member's age -> USE AGE TO SELECT THE CORRECT MEDICAID CATEGORY
        Age Rule:

        If member_age >= 65 (65 or any higher number ) -> classify as 'dual eligible'.
            lower(line_of_business) IN ('dual eligible')

        If member_age <= 64 -> classify as 'medicaid'.
            lower(line_of_business) IN ('medicaid')

        ELIF User question does not have member's age
            lower(line_of_business) IN ('dual eligible', 'medicaid')
    Clarification:  Dual eligible is the Medicaid category for members aged 65 and above. Medicaid for ages 64 and below is a different category. Always use age to determine which Medicaid category applies

    follow case-insensitive rules
    STRICTLY Provide this information to Downstream LLM
5. SELECT both `patient_location_state_code`, `patient_state_name` columns when required
6. By Default **ALWAYS** SELECT `age_nbr` to FILTER People age ; NO NEED TO SELECT any **OTHER** age related columns
7. By Default **ALWAYS** SELECT `age_bucket_description` to Filter age groups ;  NO NEED TO SELECT any **OTHER** age related columns
8. When asked questions such as "How many members were enrolled in [YEAR]?", you MUST use the following logic to capture all active members during that period:

    **Identify the relevant columns:**
    - `enrollment_effective_date`: When coverage began.
    - `enrollment_termination_date`: When coverage ended.
9. By default, ALWAYS select and use service_location_state_code for state filtering (service location); do NOT select any other state-related columns unless explicitly specified—use patient_location_state_code only when the user explicitly asks for patient residence or demographics.
10. Always select indicator (_ind) columns when the user's question is based on the description of those columns.
    Example: is_emergency_dental_ind - indicates emergency visits.

***Always STRICTLY INSTRUCT Downstream LLM TO USE** Below SQL Query to get latest year (DQ-DDMA claims)**
    - If the user explicitly specifies a year, use that exact year.
    - If NOT specified:
    SELECT MAX(YEAR(service_date)) AS latest_year
    FROM {settings.db_schema}.sem_dq_ddma.vw_sem_dq_ddma_dental_claim

STRICTLY INSTRUCT DOWNSTREAM LLM
-Always use member_id to join the vw_sem_dq_ddma_dental_claim, vw_sem_dq_ddma_dental_encounter, and vw_sem_dq_ddma_dental_enrollment tables.
-For visit-level logic, always join service_date from the claims table 'vw_sem_dq_ddma_dental_claim' with encounter_date from the encounters table 'vw_sem_dq_ddma_dental_encounter'.
-Always evaluate all line_surface code columns using OR conditions when filtering by tooth surface.

    Example:

    line_surface_1_code = 'O'
    OR line_surface_2_code = 'O'
    OR line_surface_3_code = 'O'
    OR line_surface_4_code = 'O'
    OR line_surface_5_code = 'O'
Rule: All dental and medical procedures must be queried from dental claims only. Always include lower(claim_type) = 'dental' in the WHERE clause.
"""
